import type { Task } from "../types";

/**
 * Алгебра: показательные/логарифмические уравнения и неравенства,
 * тригонометрия (ЕГЭ профиль №6, №7, №13, №15).
 */
export const algebraTasks: Task[] = [
  {
    id: "alg-exp-power-of-3",
    topic: "algebra",
    examNumber: 6,
    examLevel: "профиль",
    subtopic: "Показательное уравнение",
    difficulty: "easy",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Решите уравнение $3^{x-2} = 27$.",
    answer: { kind: "numeric", value: 5, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "Представьте 27 как степень 3." },
      { level: 2, title: "План", body: "$27 = 3^3$, тогда $3^{x-2} = 3^3 \\Rightarrow x - 2 = 3$." },
      { level: 3, title: "Разбор", body: "$x - 2 = 3$, $x = 5$." },
    ],
    solution: [
      "$27 = 3^3$, поэтому уравнение принимает вид $3^{x-2} = 3^3$.",
      "Основания равны, значит $x - 2 = 3$.",
      "$x = 5$.",
    ],
    relatedHandbookTopics: ["hb-algebra-exp-log"],
  },
  {
    id: "alg-exp-equal-bases",
    topic: "algebra",
    examNumber: 6,
    examLevel: "профиль",
    subtopic: "Показательное уравнение",
    difficulty: "easy",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Решите уравнение $5^{2x-1} = 125$.",
    answer: { kind: "numeric", value: 2, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "$125 = 5^3$." },
      { level: 2, title: "План", body: "Приравняйте показатели: $2x - 1 = 3$." },
      { level: 3, title: "Разбор", body: "$2x = 4$, $x = 2$." },
    ],
    solution: [
      "$5^{2x-1} = 5^3$.",
      "$2x - 1 = 3 \\Rightarrow x = 2$.",
    ],
    relatedHandbookTopics: ["hb-algebra-exp-log"],
  },
  {
    id: "alg-exp-substitution",
    topic: "algebra",
    examNumber: 6,
    examLevel: "профиль",
    subtopic: "Показательное уравнение",
    difficulty: "medium",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Решите уравнение $2^{2x} - 5 \\cdot 2^x + 4 = 0$. Если уравнение имеет несколько корней, в ответе укажите больший.",
    answer: { kind: "numeric", value: 2, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "Введите замену $t = 2^x$, $t > 0$." },
      { level: 2, title: "План", body: "Получится $t^2 - 5t + 4 = 0$. Корни: $t = 1$ и $t = 4$." },
      { level: 3, title: "Разбор", body: "$2^x = 1 \\Rightarrow x = 0$; $2^x = 4 \\Rightarrow x = 2$. Больший корень — $x = 2$." },
    ],
    solution: [
      "Замена $t = 2^x > 0$. Уравнение: $t^2 - 5t + 4 = 0$.",
      "По теореме Виета корни $t_1 = 1$ и $t_2 = 4$.",
      "$2^x = 1 \\Rightarrow x = 0$. $2^x = 4 \\Rightarrow x = 2$.",
      "Больший корень — 2.",
    ],
    relatedHandbookTopics: ["hb-algebra-exp-log"],
  },
  {
    id: "alg-log-simple",
    topic: "algebra",
    examNumber: 6,
    examLevel: "профиль",
    subtopic: "Логарифмическое уравнение",
    difficulty: "easy",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Решите уравнение $\\log_2 (x - 3) = 4$.",
    answer: { kind: "numeric", value: 19, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "По определению логарифма $x - 3 = 2^4$." },
      { level: 2, title: "План", body: "$2^4 = 16$, тогда $x = 19$." },
      { level: 3, title: "Разбор", body: "Проверка ОДЗ: $x - 3 > 0 \\Rightarrow x > 3$. $x = 19$ подходит." },
    ],
    solution: [
      "По определению логарифма: $x - 3 = 2^4 = 16$.",
      "$x = 19$. ОДЗ: $x > 3$ — выполнено.",
    ],
    relatedHandbookTopics: ["hb-algebra-exp-log"],
  },
  {
    id: "alg-log-product",
    topic: "algebra",
    examNumber: 6,
    examLevel: "профиль",
    subtopic: "Логарифмическое уравнение",
    difficulty: "medium",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Решите уравнение $\\log_3 (x^2 - 2x) = 1$.",
    answer: { kind: "numeric", value: 3, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "$x^2 - 2x = 3^1 = 3$." },
      { level: 2, title: "План", body: "$x^2 - 2x - 3 = 0$. Корни $x = 3$ и $x = -1$." },
      { level: 3, title: "Разбор", body: "Проверка ОДЗ: нужно $x^2 - 2x > 0$, то есть $x < 0$ или $x > 2$. Подходят оба корня. Если уравнение имеет несколько корней, обычно нужен наибольший — $x = 3$." },
    ],
    solution: [
      "$x^2 - 2x = 3$. Уравнение: $x^2 - 2x - 3 = 0$.",
      "Корни: $x = 3$ и $x = -1$ — оба удовлетворяют ОДЗ.",
      "Больший корень — 3.",
    ],
    relatedHandbookTopics: ["hb-algebra-exp-log"],
  },
  {
    id: "alg-log-inequality",
    topic: "algebra",
    examNumber: 15,
    examLevel: "профиль",
    subtopic: "Логарифмическое неравенство",
    difficulty: "hard",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Решите неравенство $\\log_2 (x - 1) \\leqslant 3$. В ответе укажите длину промежутка решений.",
    answer: { kind: "numeric", value: 8, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "Основание $2 > 1$ — знак неравенства сохраняется." },
      { level: 2, title: "План", body: "$0 < x - 1 \\leqslant 2^3$, то есть $1 < x \\leqslant 9$." },
      { level: 3, title: "Разбор", body: "Длина промежутка $(1; 9]$ равна $9 - 1 = 8$." },
    ],
    solution: [
      "ОДЗ: $x - 1 > 0 \\Rightarrow x > 1$.",
      "$\\log_2(x-1) \\leqslant 3 \\iff x - 1 \\leqslant 2^3 = 8$, то есть $x \\leqslant 9$.",
      "Решение: $1 < x \\leqslant 9$, длина $9 - 1 = 8$.",
    ],
    relatedHandbookTopics: ["hb-algebra-exp-log"],
  },
  {
    id: "alg-trig-cos-from-sin",
    topic: "algebra",
    examNumber: 7,
    examLevel: "профиль",
    subtopic: "Тригонометрия",
    difficulty: "easy",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Найдите $\\cos \\alpha$, если $\\sin \\alpha = 0{,}6$ и $\\alpha \\in \\left(\\dfrac{\\pi}{2}; \\pi\\right)$.",
    answer: { kind: "numeric", value: -0.8, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "Воспользуйтесь $\\sin^2\\alpha + \\cos^2\\alpha = 1$." },
      { level: 2, title: "План", body: "$\\cos^2\\alpha = 1 - 0{,}36 = 0{,}64$." },
      { level: 3, title: "Разбор", body: "Во второй четверти $\\cos < 0$, значит $\\cos\\alpha = -0{,}8$." },
    ],
    solution: [
      "$\\cos^2\\alpha = 1 - \\sin^2\\alpha = 1 - 0{,}36 = 0{,}64$.",
      "$|\\cos\\alpha| = 0{,}8$. Во второй четверти $\\cos\\alpha < 0$.",
      "$\\cos\\alpha = -0{,}8$.",
    ],
    relatedHandbookTopics: ["hb-algebra-trigonometry"],
  },
  {
    id: "alg-trig-double-angle",
    topic: "algebra",
    examNumber: 7,
    examLevel: "профиль",
    subtopic: "Тригонометрия",
    difficulty: "easy",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Найдите $\\sin 2\\alpha$, если $\\sin\\alpha = \\dfrac{3}{5}$ и $\\cos\\alpha = \\dfrac{4}{5}$.",
    answer: { kind: "numeric", value: 0.96, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "$\\sin 2\\alpha = 2 \\sin\\alpha \\cos\\alpha$." },
      { level: 2, title: "План", body: "$2 \\cdot \\dfrac{3}{5} \\cdot \\dfrac{4}{5} = \\dfrac{24}{25}$." },
      { level: 3, title: "Разбор", body: "$\\dfrac{24}{25} = 0{,}96$." },
    ],
    solution: [
      "$\\sin 2\\alpha = 2 \\sin\\alpha \\cos\\alpha = 2 \\cdot \\dfrac{3}{5} \\cdot \\dfrac{4}{5} = \\dfrac{24}{25} = 0{,}96$.",
    ],
    relatedHandbookTopics: ["hb-algebra-trigonometry"],
  },
  {
    id: "alg-trig-tan-pi",
    topic: "algebra",
    examNumber: 7,
    examLevel: "профиль",
    subtopic: "Тригонометрия",
    difficulty: "easy",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Вычислите $\\tg\\dfrac{5\\pi}{4}$.",
    answer: { kind: "numeric", value: 1, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "$\\dfrac{5\\pi}{4} = \\pi + \\dfrac{\\pi}{4}$." },
      { level: 2, title: "План", body: "$\\tg(\\pi + x) = \\tg x$." },
      { level: 3, title: "Разбор", body: "$\\tg \\dfrac{\\pi}{4} = 1$." },
    ],
    solution: [
      "$\\dfrac{5\\pi}{4} = \\pi + \\dfrac{\\pi}{4}$, $\\tg$ имеет период $\\pi$.",
      "$\\tg \\dfrac{5\\pi}{4} = \\tg \\dfrac{\\pi}{4} = 1$.",
    ],
    relatedHandbookTopics: ["hb-algebra-trigonometry"],
  },
  {
    id: "alg-trig-simple-cos",
    topic: "algebra",
    examNumber: 13,
    examLevel: "профиль",
    subtopic: "Тригонометрическое уравнение",
    difficulty: "medium",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Найдите наименьший положительный корень уравнения $\\cos x = -\\dfrac{1}{2}$.",
    answer: { kind: "numeric", value: 2.0944, tolerance: 0.005 },
    hints: [
      { level: 1, title: "Подсказка", body: "$\\cos x = -\\dfrac{1}{2} \\Rightarrow x = \\pm \\dfrac{2\\pi}{3} + 2\\pi k$." },
      { level: 2, title: "План", body: "Из положительных кандидатов: $\\dfrac{2\\pi}{3}$ и $-\\dfrac{2\\pi}{3} + 2\\pi = \\dfrac{4\\pi}{3}$." },
      { level: 3, title: "Разбор", body: "Наименьший положительный — $x = \\dfrac{2\\pi}{3} \\approx 2{,}094$." },
    ],
    solution: [
      "$\\cos x = -\\dfrac{1}{2}$. Серии корней: $x = \\dfrac{2\\pi}{3} + 2\\pi k$ и $x = -\\dfrac{2\\pi}{3} + 2\\pi k$.",
      "Положительные значения: $\\dfrac{2\\pi}{3} \\approx 2{,}094$ и $\\dfrac{4\\pi}{3} \\approx 4{,}189$.",
      "Минимальный положительный — $\\dfrac{2\\pi}{3}$.",
    ],
    relatedHandbookTopics: ["hb-algebra-trigonometry"],
  },
  {
    id: "alg-trig-simple-sin",
    topic: "algebra",
    examNumber: 13,
    examLevel: "профиль",
    subtopic: "Тригонометрическое уравнение",
    difficulty: "medium",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Решите уравнение $2\\sin x = 1$. Найдите количество корней на отрезке $[0; 2\\pi]$.",
    answer: { kind: "numeric", value: 2, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "$\\sin x = \\dfrac{1}{2}$." },
      { level: 2, title: "План", body: "Корни: $x = \\dfrac{\\pi}{6}$ и $x = \\pi - \\dfrac{\\pi}{6} = \\dfrac{5\\pi}{6}$ (на $[0; 2\\pi]$)." },
      { level: 3, title: "Разбор", body: "Оба попадают в отрезок: 2 корня." },
    ],
    solution: [
      "$\\sin x = \\dfrac{1}{2}$. На $[0; 2\\pi]$: $x = \\dfrac{\\pi}{6}$ и $x = \\dfrac{5\\pi}{6}$.",
      "Оба корня лежат в $[0; 2\\pi]$ — итого 2.",
    ],
    relatedHandbookTopics: ["hb-algebra-trigonometry"],
  },
  {
    id: "alg-trig-roots-on-segment",
    topic: "algebra",
    examNumber: 13,
    examLevel: "профиль",
    subtopic: "Тригонометрическое уравнение с отбором",
    difficulty: "hard",
    source: "Открытый банк ФИПИ (тип задания)",
    statement: "Найдите количество корней уравнения $\\sin 2x = 0$ на отрезке $[0; 2\\pi]$.",
    answer: { kind: "numeric", value: 5, tolerance: 0.001 },
    hints: [
      { level: 1, title: "Подсказка", body: "$\\sin 2x = 0 \\iff 2x = \\pi k$, то есть $x = \\dfrac{\\pi k}{2}$." },
      { level: 2, title: "План", body: "Перечислите $x$ при $k = 0, 1, 2, 3, 4$ — должны лежать в $[0; 2\\pi]$." },
      { level: 3, title: "Разбор", body: "Корни: $0,\\ \\dfrac{\\pi}{2},\\ \\pi,\\ \\dfrac{3\\pi}{2},\\ 2\\pi$ — 5 значений." },
    ],
    solution: [
      "$\\sin 2x = 0 \\iff x = \\dfrac{\\pi k}{2}$, $k \\in \\mathbb{Z}$.",
      "На $[0; 2\\pi]$: $k = 0, 1, 2, 3, 4$ дают $x = 0,\\ \\dfrac{\\pi}{2},\\ \\pi,\\ \\dfrac{3\\pi}{2},\\ 2\\pi$.",
      "Всего 5 корней.",
    ],
    relatedHandbookTopics: ["hb-algebra-trigonometry"],
  },
];
