import type { Task } from "../types";

/**
 * Экономические задачи (ЕГЭ профиль №16).
 * Сгенерировано через scripts/gen_tasks.py — не правьте файл вручную.
 */

export const economicsTasks: Task[] = [
{
  id: "econ-deposit-compound",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Вклад со сложным процентом",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "1 января 2020 года вкладчик положил в банк 200 000 рублей под 10% годовых с ежегодной капитализацией процентов. Сколько рублей будет на счёте 1 января 2023 года?",
  answer: { kind: "numeric", value: 266200, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Каждый год сумма умножается на $(1+r)$." },
    { level: 2, title: "План", body: "$S_n = S_0 \\cdot (1+r)^n$." },
    { level: 3, title: "Разбор", body: "$S = 200000 \\cdot 1{,}1^3 = 266\\,200$." },
  ],
  solution: [
    "$1{,}1^3 = 1{,}331$.",
    "$S = 200000 \\cdot 1{,}331 = 266200$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-differential-overpay",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Дифференцированные платежи",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Иван взял кредит 7,2 млн руб. на 8 месяцев по дифференцированной схеме под 2% в месяц. Каждый месяц долг уменьшается на одну и ту же сумму. Найдите переплату.",
  answer: { kind: "numeric", value: 648000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Долг каждого месяца: 7,2; 6,3; ...; 0,9 (млн)." },
    { level: 2, title: "План", body: "Переплата = сумма процентов за каждый месяц." },
    { level: 3, title: "Разбор", body: "Сумма долгов = $7{,}2 + 6{,}3 + ... + 0{,}9 = 32{,}4$. Переплата = $32{,}4 \\cdot 0{,}02 = 0{,}648$ млн = 648 000." },
  ],
  solution: [
    "Сумма остатков: $(7{,}2+0{,}9) \\cdot 8/2 = 32{,}4$ млн.",
    "Переплата: $32{,}4 \\cdot 0{,}02 \\cdot 10^6 = 648\\,000$.",
  ],
  relatedHandbookTopics: ["hb-economics-credit-differential"],
},
{
  id: "econ-annuity-payment",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Аннуитетный платёж",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "1 января 2020 года Иван взял в банке 1 000 000 рублей под 10% в месяц на 4 месяца с аннуитетной схемой (равные ежемесячные платежи, к концу 4-го месяца долг погашен). Найдите ежемесячный платёж. Ответ округлите до целого.",
  answer: { kind: "numeric", value: 315471, tolerance: 2 },
  hints: [
    { level: 1, title: "Подсказка", body: "Аннуитетное уравнение: $S \\cdot q^n = x \\cdot (q^n - 1)/(q - 1)$." },
    { level: 2, title: "План", body: "$q = 1{,}1$, $q^4 = 1{,}4641$." },
    { level: 3, title: "Разбор", body: "$x = 10^6 \\cdot 1{,}4641 \\cdot 0{,}1/0{,}4641 \\approx 315\\,471$." },
  ],
  solution: [
    "$q = 1{,}1$, $q^4 = 1{,}4641$.",
    "$x = S q^n (q-1)/(q^n - 1) \\approx 315\\,471$.",
  ],
  relatedHandbookTopics: ["hb-economics-credit-annuity"],
},
{
  id: "econ-quadratic-profit",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Оптимизация",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Прибыль зависит от количества выпущенной продукции $x$ по формуле $f(x) = -x^2 + 60x - 500$. Найдите максимальную прибыль.",
  answer: { kind: "numeric", value: 400, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Максимум квадратичной функции в вершине." },
    { level: 2, title: "План", body: "$x_0 = 30$." },
    { level: 3, title: "Разбор", body: "$f(30) = -900 + 1800 - 500 = 400$." },
  ],
  solution: [
    "Вершина: $x_0 = 60/2 = 30$.",
    "$f(30) = -900 + 1800 - 500 = 400$.",
  ],
  relatedHandbookTopics: ["hb-economics-optimization"],
},
{
  id: "econ-deposit-monthly",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Сложный процент с пополнением",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вкладчик открыл вклад на 100 000 руб. под 10% годовых. Каждый год в конце года он докладывает 50 000 руб. Сколько рублей будет на счёте через 2 года? (капитализация ежегодная, пополнение — после начисления процентов)",
  answer: { kind: "numeric", value: 226000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "За первый год: 100000 * 1,1 + 50000." },
    { level: 2, title: "План", body: "За второй год: от полученной суммы снова * 1,1 + 50000." },
    { level: 3, title: "Разбор", body: "$S_1 = 160000$, $S_2 = 160000 \\cdot 1{,}1 + 50000 = 226000$." },
  ],
  solution: [
    "Год 1: $100000 \\cdot 1{,}1 + 50000 = 160000$.",
    "Год 2: $160000 \\cdot 1{,}1 + 50000 = 226000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-credit-table",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Кредит по таблице долгов",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В январе каждого из 3 лет банк начисляет 30% на сумму долга. В феврале клиент вносит сумму. В начале 1-го года долг 1 млн. После платежей остатки становятся: после 1-го года — 0,6 млн; после 2-го — 0,3 млн; после 3-го — 0. Найдите суммарный внесённый платёж. Ответ в млн руб.",
  answer: { kind: "numeric", value: 1.57, tolerance: 0.005 },
  hints: [
    { level: 1, title: "Подсказка", body: "Каждый год долг растёт на 30%, затем вычитают платёж." },
    { level: 2, title: "План", body: "$\\text{платёж}_k = 1{,}3 \\cdot D_{k-1} - D_k$." },
    { level: 3, title: "Разбор", body: "Платёжи: $1{,}3-0{,}6 = 0{,}7$; $0{,}78-0{,}3 = 0{,}48$; $0{,}39-0 = 0{,}39$. Сумма: $0{,}7+0{,}48+0{,}39 = 1{,}57$." },
  ],
  solution: [
    "Платёж 1: $1{,}3 \\cdot 1 - 0{,}6 = 0{,}7$.",
    "Платёж 2: $1{,}3 \\cdot 0{,}6 - 0{,}3 = 0{,}48$.",
    "Платёж 3: $1{,}3 \\cdot 0{,}3 - 0 = 0{,}39$.",
    "Сумма: $0{,}7 + 0{,}48 + 0{,}39 = 1{,}57$ млн.",
  ],
  relatedHandbookTopics: ["hb-economics-credit-differential"],
},
{
  id: "econ-deposit-monthly-cap",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Вклад с ежемесячной капитализацией",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вкладчик положил 100 000 рублей под 12% годовых с ежемесячной капитализацией (каждый месяц прибавляется $1\\%$ от текущей суммы). Какая сумма будет через 2 месяца? Округлите до целого.",
  answer: { kind: "numeric", value: 102010, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Месячная ставка: 1%." },
    { level: 2, title: "План", body: "$S = 100000 \\cdot 1{,}01^n$." },
    { level: 3, title: "Разбор", body: "$S = 100000 \\cdot 1{,}0201 = 102010$." },
  ],
  solution: [
    "$1{,}01^2 = 1{,}0201$.",
    "$S = 102010$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-loan-simple",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Простой кредит",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Иван взял 600 000 руб. под 20% годовых на 1 год. Сколько рублей он переплатит банку, если погасит кредит одним платежом в конце срока?",
  answer: { kind: "numeric", value: 120000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Долг к концу года: $S \\cdot 1{,}2$." },
    { level: 2, title: "План", body: "Переплата = $S \\cdot 1{,}2 - S = S \\cdot 0{,}2$." },
    { level: 3, title: "Разбор", body: "$600000 \\cdot 0{,}2 = 120000$." },
  ],
  solution: [
    "Долг: $720000$.",
    "Переплата: $120000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-deposit-4y",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Вклад со сложным процентом",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вкладчик положил 50 000 рублей под 8% годовых с ежегодной капитализацией. Сколько рублей будет на счёте через 2 года? Ответ округлите до целого.",
  answer: { kind: "numeric", value: 58320, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S_n = S_0 (1+r)^n$." },
    { level: 2, title: "План", body: "$1{,}08^2 = 1{,}1664$." },
    { level: 3, title: "Разбор", body: "$S = 50000 \\cdot 1{,}1664 = 58320$." },
  ],
  solution: [
    "$S = 50000 \\cdot 1{,}1664 = 58320$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-deposit-5y",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Вклад со сложным процентом",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В банке открыли вклад 400 000 руб. под 15% годовых на 2 года. Сколько рублей будет на счёте в конце срока? Ответ округлите до целого.",
  answer: { kind: "numeric", value: 529000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = 400000 \\cdot 1{,}15^2$." },
    { level: 2, title: "План", body: "$1{,}15^2 = 1{,}3225$." },
    { level: 3, title: "Разбор", body: "$S = 400000 \\cdot 1{,}3225 = 529\\,000$." },
  ],
  solution: [
    "$S = 400000 \\cdot 1{,}3225 = 529000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-loan-year-half",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Простой кредит",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Кредит 300 000 руб. под 12% годовых на 6 месяцев с единовременным возвратом. Сколько составит переплата?",
  answer: { kind: "numeric", value: 18000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "За полгода ставка 6%." },
    { level: 2, title: "План", body: "$300000 \\cdot 0{,}06$." },
    { level: 3, title: "Разбор", body: "Переплата = $18\\,000$." },
  ],
  solution: [
    "Ставка за 6 мес = 6%.",
    "Переплата = $300000 \\cdot 0{,}06 = 18000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-markup",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Наценка и скидка",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Магазин закупил товар по 400 рублей и продаёт с наценкой 35%. По какой цене магазин продаёт товар?",
  answer: { kind: "numeric", value: 540, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Наценка добавляется к цене." },
    { level: 2, title: "План", body: "Новая цена = $400 \\cdot 1{,}35$." },
    { level: 3, title: "Разбор", body: "$400 \\cdot 1{,}35 = 540$." },
  ],
  solution: [
    "$400 \\cdot 1{,}35 = 540$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-discount-sequential",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Наценка и скидка",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Товар стоил 1000 рублей. Сначала цену подняли на 20%, затем снизили на 20%. Какая стала конечная цена?",
  answer: { kind: "numeric", value: 960, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Коэффициенты $1{,}2$ и $0{,}8$." },
    { level: 2, title: "План", body: "Перемножить." },
    { level: 3, title: "Разбор", body: "$1000 \\cdot 1{,}2 \\cdot 0{,}8 = 960$." },
  ],
  solution: [
    "$1000 \\cdot 1{,}2 = 1200$.",
    "$1200 \\cdot 0{,}8 = 960$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-inflation-2y",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Инфляция",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Цена хлеба растёт на 8% ежегодно. Сейчас буханка стоит 50 рублей. Сколько она будет стоить через 3 года? Ответ округлите до целого.",
  answer: { kind: "numeric", value: 63, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "$50 \\cdot 1{,}08^3$." },
    { level: 2, title: "План", body: "$1{,}08^3 \\approx 1{,}2597$." },
    { level: 3, title: "Разбор", body: "$50 \\cdot 1{,}2597 \\approx 63$." },
  ],
  solution: [
    "$1{,}08^3 = 1{,}2597$.",
    "$50 \\cdot 1{,}2597 \\approx 63$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-goal-save",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Накопительный вклад",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Чтобы накопить 605 000 рублей под 10% годовых (капитализация ежегодная), сколько нужно положить сейчас? Срок — 2 года. Ответ округлите до целого.",
  answer: { kind: "numeric", value: 500000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S_n = S_0 (1+r)^n$." },
    { level: 2, title: "План", body: "$S_0 = S_n / (1+r)^n$." },
    { level: 3, title: "Разбор", body: "$S_0 = 605000 / 1{,}21 = 500\\,000$." },
  ],
  solution: [
    "$1{,}1^2 = 1{,}21$.",
    "$S_0 = 605000/1{,}21 = 500000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-diff-3",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Дифференцированные платежи",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Кредит 900 000 руб. на 3 месяца под 5% в месяц с дифференцированными платежами (долг уменьшается каждый месяц на одну и ту же сумму). Найдите сумму переплаты в рублях.",
  answer: { kind: "numeric", value: 90000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Долги: 900, 600, 300 тыс." },
    { level: 2, title: "План", body: "Проценты: $900 \\cdot 0{,}05 + 600 \\cdot 0{,}05 + 300 \\cdot 0{,}05 = 1800 \\cdot 0{,}05$ тыс." },
    { level: 3, title: "Разбор", body: "$1800 \\cdot 0{,}05 = 90$ тыс = 90 000 руб." },
  ],
  solution: [
    "Сумма долгов: $900 + 600 + 300 = 1800$ тыс.",
    "$0{,}05 \\cdot 1800 = 90$ тыс = $90000$.",
  ],
  relatedHandbookTopics: ["hb-economics-credit-differential"],
},
{
  id: "econ-annuity-2m",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Аннуитетный платёж",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Кредит 100 000 рублей на 2 месяца под 10% в месяц с аннуитетной схемой. Найдите ежемесячный платёж в рублях. Округлите до целого.",
  answer: { kind: "numeric", value: 57619, tolerance: 2 },
  hints: [
    { level: 1, title: "Подсказка", body: "$x = S q^n (q-1)/(q^n - 1)$." },
    { level: 2, title: "План", body: "$q^2 = 1{,}21$." },
    { level: 3, title: "Разбор", body: "$x = 100000 \\cdot 1{,}21 \\cdot 0{,}1/0{,}21 \\approx 57619$." },
  ],
  solution: [
    "$q^n = 1{,}21$.",
    "$x = 100000 \\cdot 1{,}21 \\cdot 0{,}1/0{,}21 \\approx 57619$.",
  ],
  relatedHandbookTopics: ["hb-economics-credit-annuity"],
},
{
  id: "econ-markup-loss",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Цена и процент",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "После двух повышений цены на 10% каждое, товар стоит 1452 рубля. Сколько он стоил изначально?",
  answer: { kind: "numeric", value: 1200, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S \\cdot 1{,}1^2 = 1452$." },
    { level: 2, title: "План", body: "$S = 1452/1{,}21$." },
    { level: 3, title: "Разбор", body: "$S = 1200$." },
  ],
  solution: [
    "$1{,}1^2 = 1{,}21$.",
    "$S = 1452/1{,}21 = 1200$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-tax-net",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Налоги",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Зарплата до налогов 50 000 рублей. Ставка НДФЛ 13%. Сколько рублей получит на руки сотрудник?",
  answer: { kind: "numeric", value: 43500, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "Налог = 13% от зарплаты." },
    { level: 2, title: "План", body: "На руки = $50000 \\cdot 0{,}87$." },
    { level: 3, title: "Разбор", body: "$50000 \\cdot 0{,}87 = 43500$." },
  ],
  solution: [
    "$50000 \\cdot 0{,}87 = 43500$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-salary-increase",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Проценты",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Зарплату повысили на 20%, и она стала 60 000 рублей. Какая была зарплата до повышения?",
  answer: { kind: "numeric", value: 50000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S \\cdot 1{,}2 = 60000$." },
    { level: 2, title: "План", body: "$S = 60000/1{,}2$." },
    { level: 3, title: "Разбор", body: "$S = 50000$." },
  ],
  solution: [
    "$S = 60000/1{,}2 = 50000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-quad-max-price",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Оптимизация",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Спрос на товар задан функцией $q(p) = 100 - 2p$ (единиц при цене $p$ руб.). Выручка $R(p) = p \\cdot q(p)$. Найдите максимальное значение выручки.",
  answer: { kind: "numeric", value: 1250, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "$R(p) = 100p - 2p^2$." },
    { level: 2, title: "План", body: "Вершина в $p_0 = 100/4 = 25$." },
    { level: 3, title: "Разбор", body: "$R(25) = 2500 - 1250 = 1250$." },
  ],
  solution: [
    "$R(p) = 100p - 2p^2$.",
    "$p_0 = 25$, $R(25) = 1250$.",
  ],
  relatedHandbookTopics: ["hb-economics-optimization"],
},
{
  id: "econ-quad-min-cost",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Оптимизация",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Суммарные затраты на выпуск $x$ единиц: $C(x) = x^2 - 40x + 500$. При каком $x$ затраты минимальны и чему равны?",
  answer: { kind: "numeric", value: 100, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "Минимум квадратичной функции в вершине." },
    { level: 2, title: "План", body: "$x_0 = 40/2 = 20$." },
    { level: 3, title: "Разбор", body: "$C(20) = 400 - 800 + 500 = 100$." },
  ],
  solution: [
    "$x_0 = 20$.",
    "$C(20) = 100$.",
  ],
  relatedHandbookTopics: ["hb-economics-optimization"],
},
{
  id: "econ-break-even",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Точка безубыточности",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Постоянные издержки фирмы 10 000 руб./мес. Переменные издержки на единицу — 50 руб., цена продажи — 150 руб. Сколько единиц нужно продать за месяц, чтобы не быть в убытке?",
  answer: { kind: "numeric", value: 100, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "Выручка = издержки." },
    { level: 2, title: "План", body: "$150x = 10000 + 50x$." },
    { level: 3, title: "Разбор", body: "$100x = 10000$, $x = 100$." },
  ],
  solution: [
    "$150x = 10000 + 50x$.",
    "$x = 100$.",
  ],
  relatedHandbookTopics: ["hb-economics-optimization"],
},
{
  id: "econ-interest-diff",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Сравнение вкладов",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вклад A: 100 000 руб. под 10% годовых с ежегодной капитализацией на 2 года. Вклад B: простые проценты 11% на 2 года. Насколько вклад A больше вклада B? Ответ в рублях.",
  answer: { kind: "numeric", value: -1000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Вклад A: $100000 \\cdot 1{,}1^2 = 121000$." },
    { level: 2, title: "План", body: "Вклад B: $100000 \\cdot (1 + 2 \\cdot 0{,}11) = 122000$." },
    { level: 3, title: "Разбор", body: "Разность: $A - B = 121000 - 122000 = -1000$, т.е. A меньше на 1000." },
  ],
  solution: [
    "A: $100000 \\cdot 1{,}21 = 121000$.",
    "B: $100000 \\cdot 1{,}22 = 122000$.",
    "$A - B = -1000$.",
  ],
  relatedHandbookTopics: ["hb-economics-strategy"],
},
{
  id: "econ-annuity-6m",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Аннуитетный платёж",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Кредит 500 000 руб. на 3 месяца под 5% в месяц с аннуитетной схемой. Найдите ежемесячный платёж. Округлите до целого.",
  answer: { kind: "numeric", value: 183602, tolerance: 3 },
  hints: [
    { level: 1, title: "Подсказка", body: "$x = S q^n (q-1)/(q^n - 1)$." },
    { level: 2, title: "План", body: "$q = 1{,}05$, $q^3 = 1{,}157625$." },
    { level: 3, title: "Разбор", body: "$x = 500000 \\cdot 1{,}157625 \\cdot 0{,}05 / 0{,}157625 \\approx 183\\,602$." },
  ],
  solution: [
    "$q^3 = 1{,}157625$.",
    "$x \\approx 500000 \\cdot 1{,}157625 \\cdot 0{,}05/0{,}157625 \\approx 183602$.",
  ],
  relatedHandbookTopics: ["hb-economics-credit-annuity"],
},
{
  id: "econ-interest-monthly-compare",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Сравнение вкладов",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Во сколько раз увеличится вклад за 1 год под 12% годовых с ежемесячной капитализацией? Ответ округлите до сотых.",
  answer: { kind: "numeric", value: 1.1268, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Месячная ставка 1%, $n = 12$." },
    { level: 2, title: "План", body: "$k = 1{,}01^{12}$." },
    { level: 3, title: "Разбор", body: "$1{,}01^{12} \\approx 1{,}1268$." },
  ],
  solution: [
    "$1{,}01^{12} \\approx 1{,}1268$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-fund-grow",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Накопительный вклад",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В конце каждого из 3 лет на счёт вкладывают по 100 000 рублей. На всю сумму в конце года начисляются 10% годовых. Сколько будет на счёте через 3 года? (взносы делаются после капитализации)",
  answer: { kind: "numeric", value: 331000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Каждый взнос растёт разное количество лет." },
    { level: 2, title: "План", body: "Первый взнос растёт 2 года, второй — 1 год, третий — 0." },
    { level: 3, title: "Разбор", body: "$100000 \\cdot (1{,}1^2 + 1{,}1 + 1) = 100000 \\cdot 3{,}31 = 331000$." },
  ],
  solution: [
    "$1{,}1^2 + 1{,}1 + 1 = 1{,}21+1{,}1+1 = 3{,}31$.",
    "$100000 \\cdot 3{,}31 = 331000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-final-after-fall",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Проценты",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Акции подорожали на 25%, а затем подешевели на 20%. На сколько процентов изменилась исходная цена?",
  answer: { kind: "numeric", value: 0, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "Коэффициенты $1{,}25$ и $0{,}8$." },
    { level: 2, title: "План", body: "Перемножить." },
    { level: 3, title: "Разбор", body: "$1{,}25 \\cdot 0{,}8 = 1$. Изменение на 0%." },
  ],
  solution: [
    "$1{,}25 \\cdot 0{,}8 = 1$.",
    "Изменения нет, 0%.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-invest-shares",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Инвестиции",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Инвестор вложил 200 000 руб. в две акции: A — 60%, B — 40%. Акция A выросла на 30%, B упала на 10%. Найдите стоимость портфеля в рублях.",
  answer: { kind: "numeric", value: 228000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "A = $120000 \\cdot 1{,}3$. B = $80000 \\cdot 0{,}9$." },
    { level: 2, title: "План", body: "Суммировать." },
    { level: 3, title: "Разбор", body: "$156000 + 72000 = 228000$." },
  ],
  solution: [
    "A: $120000 \\cdot 1{,}3 = 156000$.",
    "B: $80000 \\cdot 0{,}9 = 72000$.",
    "Итого: $228000$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
{
  id: "econ-double-years",
  topic: "economics",
  examNumber: 16,
  examLevel: "профиль",
  subtopic: "Накопление",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Через сколько лет сумма удвоится при ставке 20% годовых (ежегодная капитализация)? Дайте наименьшее целое число лет, при котором сумма точно удвоилась.",
  answer: { kind: "numeric", value: 4, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "$1{,}2^n \\ge 2$." },
    { level: 2, title: "План", body: "$1{,}2^3 = 1{,}728$, $1{,}2^4 = 2{,}0736$." },
    { level: 3, title: "Разбор", body: "Наименьшее целое $n = 4$." },
  ],
  solution: [
    "$1{,}2^3 = 1{,}728 < 2$.",
    "$1{,}2^4 = 2{,}07 \\ge 2$.",
    "$n = 4$.",
  ],
  relatedHandbookTopics: ["hb-economics-deposits"],
},
];
