import type { Task } from "../types";

/**
 * Геометрия: планиметрия (№1), векторы (№2), стереометрия (№3).
 * Сгенерировано через scripts/gen_tasks.py — не правьте файл вручную.
 */

export const geometryTasks: Task[] = [
{
  id: "geom-right-hypot",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Теорема Пифагора",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В прямоугольном треугольнике катеты равны 3 и 4. Найдите гипотенузу.",
  answer: { kind: "numeric", value: 5, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Теорема Пифагора: $c^2 = a^2 + b^2$." },
    { level: 2, title: "План", body: "$c^2 = 9 + 16 = 25$." },
    { level: 3, title: "Разбор", body: "$c = 5$." },
  ],
  solution: [
    "$c^2 = 3^2 + 4^2 = 25$.",
    "$c = 5$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-right-leg",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Теорема Пифагора",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В прямоугольном треугольнике гипотенуза равна 13, один из катетов — 5. Найдите второй катет.",
  answer: { kind: "numeric", value: 12, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$b^2 = c^2 - a^2$." },
    { level: 2, title: "План", body: "$b^2 = 169 - 25 = 144$." },
    { level: 3, title: "Разбор", body: "$b = 12$." },
  ],
  solution: [
    "$b^2 = 13^2 - 5^2 = 169 - 25 = 144$.",
    "$b = 12$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-triangle-area",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Площадь треугольника",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Основание треугольника 10, высота к этому основанию 6. Найдите его площадь.",
  answer: { kind: "numeric", value: 30, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = \\dfrac{1}{2} a h$." },
    { level: 2, title: "План", body: "$S = 0{,}5 \\cdot 10 \\cdot 6$." },
    { level: 3, title: "Разбор", body: "$S = 30$." },
  ],
  solution: [
    "$S = 0{,}5 \\cdot 10 \\cdot 6 = 30$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-right-area",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Площадь треугольника",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В прямоугольном треугольнике катеты равны 6 и 8. Найдите площадь.",
  answer: { kind: "numeric", value: 24, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = \\dfrac{1}{2} a b$ (для прямоугольного)." },
    { level: 2, title: "План", body: "$S = 0{,}5 \\cdot 6 \\cdot 8$." },
    { level: 3, title: "Разбор", body: "$S = 24$." },
  ],
  solution: [
    "$S = 0{,}5 \\cdot 6 \\cdot 8 = 24$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-triangle-heron",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Формула Герона",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Стороны треугольника равны 13, 14, 15. Найдите его площадь.",
  answer: { kind: "numeric", value: 84, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Формула Герона: $S = \\sqrt{p(p-a)(p-b)(p-c)}$, $p$ — полупериметр." },
    { level: 2, title: "План", body: "$p = (13+14+15)/2 = 21$." },
    { level: 3, title: "Разбор", body: "$S = \\sqrt{21 \\cdot 8 \\cdot 7 \\cdot 6} = \\sqrt{7056} = 84$." },
  ],
  solution: [
    "$p = 21$.",
    "$S^2 = 21 \\cdot 8 \\cdot 7 \\cdot 6 = 7056$.",
    "$S = 84$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-parallelogram-area",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Площадь параллелограмма",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "У параллелограмма сторона 12, высота к ней 7. Найдите площадь.",
  answer: { kind: "numeric", value: 84, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = a h$." },
    { level: 2, title: "План", body: "$S = 12 \\cdot 7$." },
    { level: 3, title: "Разбор", body: "$S = 84$." },
  ],
  solution: [
    "$S = 12 \\cdot 7 = 84$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-rhombus-diags",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Площадь ромба",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Диагонали ромба равны 10 и 24. Найдите его площадь.",
  answer: { kind: "numeric", value: 120, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = \\dfrac{1}{2} d_1 d_2$." },
    { level: 2, title: "План", body: "$S = 0{,}5 \\cdot 10 \\cdot 24$." },
    { level: 3, title: "Разбор", body: "$S = 120$." },
  ],
  solution: [
    "$S = (10 \\cdot 24)/2 = 120$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-trapezoid-area",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Площадь трапеции",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В трапеции основания равны 6 и 10, высота — 4. Найдите площадь.",
  answer: { kind: "numeric", value: 32, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = \\dfrac{a+b}{2} h$." },
    { level: 2, title: "План", body: "$S = (6+10)/2 \\cdot 4 = 8 \\cdot 4$." },
    { level: 3, title: "Разбор", body: "$S = 32$." },
  ],
  solution: [
    "$S = \\dfrac{6+10}{2} \\cdot 4 = 32$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-rect-area",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Площадь прямоугольника",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Стороны прямоугольника 9 и 15. Найдите его площадь.",
  answer: { kind: "numeric", value: 135, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = a b$." },
    { level: 2, title: "План", body: "$9 \\cdot 15$." },
    { level: 3, title: "Разбор", body: "$S = 135$." },
  ],
  solution: [
    "$S = 9 \\cdot 15 = 135$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-square-diagonal",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Диагональ квадрата",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Сторона квадрата равна 5. Найдите его диагональ. Ответ округлите до сотых.",
  answer: { kind: "numeric", value: 7.07, tolerance: 0.02 },
  hints: [
    { level: 1, title: "Подсказка", body: "Диагональ квадрата: $d = a \\sqrt{2}$." },
    { level: 2, title: "План", body: "$d = 5\\sqrt{2}$." },
    { level: 3, title: "Разбор", body: "$\\sqrt{2} \\approx 1{,}414$; $5 \\cdot 1{,}414 = 7{,}07$." },
  ],
  solution: [
    "$d = a\\sqrt{2} = 5\\sqrt{2} \\approx 7{,}07$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-circle-area",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Круг: площадь",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Радиус круга равен 5. Найдите площадь круга. Ответ через $\\pi$: укажите коэффициент перед $\\pi$.",
  answer: { kind: "numeric", value: 25, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = \\pi r^2$." },
    { level: 2, title: "План", body: "$r^2 = 25$." },
    { level: 3, title: "Разбор", body: "$S = 25\\pi$; коэффициент = 25." },
  ],
  solution: [
    "$S = \\pi \\cdot 25$.",
    "Коэффициент = 25.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-circle-circumference",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Круг: длина",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите длину окружности радиуса 7. Ответ укажите как коэффициент перед $\\pi$.",
  answer: { kind: "numeric", value: 14, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$L = 2\\pi r$." },
    { level: 2, title: "План", body: "Коэффициент перед $\\pi$: $2r$." },
    { level: 3, title: "Разбор", body: "$2 \\cdot 7 = 14$." },
  ],
  solution: [
    "$L = 2\\pi \\cdot 7 = 14\\pi$.",
    "Коэффициент = 14.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-inscribed-angle",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Вписанный угол",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Центральный угол равен 80°. Найдите вписанный угол, опирающийся на ту же дугу. Ответ в градусах.",
  answer: { kind: "numeric", value: 40, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "Вписанный угол = половина центрального." },
    { level: 2, title: "План", body: "$\\alpha = \\beta/2$." },
    { level: 3, title: "Разбор", body: "$40°$." },
  ],
  solution: [
    "$\\alpha = 80/2 = 40°$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-isoceles-angle",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Равнобедренный треугольник",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В равнобедренном треугольнике угол при вершине равен 40°. Найдите каждый из углов при основании. Ответ в градусах.",
  answer: { kind: "numeric", value: 70, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сумма углов треугольника 180°." },
    { level: 2, title: "План", body: "$(180 - 40)/2$." },
    { level: 3, title: "Разбор", body: "$70°$." },
  ],
  solution: [
    "$(180 - 40)/2 = 70°$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-30-60-90",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Прямоугольный треугольник",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В прямоугольном треугольнике острый угол равен 30°, гипотенуза равна 12. Найдите меньший катет.",
  answer: { kind: "numeric", value: 6, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Против 30° лежит катет, равный половине гипотенузы." },
    { level: 2, title: "План", body: "$a = c/2$." },
    { level: 3, title: "Разбор", body: "$12/2 = 6$." },
  ],
  solution: [
    "Катет против 30° = c/2 = 6.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-cube-volume",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Куб: объём",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Ребро куба равно 5. Найдите его объём.",
  answer: { kind: "numeric", value: 125, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$V = a^3$." },
    { level: 2, title: "План", body: "$5^3$." },
    { level: 3, title: "Разбор", body: "$V = 125$." },
  ],
  solution: [
    "$V = 5^3 = 125$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-cube-surface",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Куб: площадь поверхности",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Ребро куба равно 4. Найдите полную площадь поверхности.",
  answer: { kind: "numeric", value: 96, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = 6 a^2$." },
    { level: 2, title: "План", body: "$6 \\cdot 16$." },
    { level: 3, title: "Разбор", body: "$S = 96$." },
  ],
  solution: [
    "$S = 6 \\cdot 16 = 96$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-parallel-volume",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Параллелепипед",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Измерения прямоугольного параллелепипеда 3, 4, 5. Найдите его объём.",
  answer: { kind: "numeric", value: 60, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$V = a b c$." },
    { level: 2, title: "План", body: "$3 \\cdot 4 \\cdot 5$." },
    { level: 3, title: "Разбор", body: "$V = 60$." },
  ],
  solution: [
    "$V = 3 \\cdot 4 \\cdot 5 = 60$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-prism-volume",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Призма: объём",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Площадь основания призмы 12, высота — 7. Найдите объём.",
  answer: { kind: "numeric", value: 84, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$V = S_{\\text{осн}} \\cdot h$." },
    { level: 2, title: "План", body: "$12 \\cdot 7$." },
    { level: 3, title: "Разбор", body: "$V = 84$." },
  ],
  solution: [
    "$V = 12 \\cdot 7 = 84$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-pyramid-volume",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Пирамида: объём",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Площадь основания пирамиды 15, высота — 6. Найдите объём.",
  answer: { kind: "numeric", value: 30, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$V = \\dfrac{1}{3} S_{\\text{осн}} h$." },
    { level: 2, title: "План", body: "$(15 \\cdot 6)/3$." },
    { level: 3, title: "Разбор", body: "$V = 30$." },
  ],
  solution: [
    "$V = (15 \\cdot 6)/3 = 30$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-cylinder-volume",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Цилиндр: объём",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Радиус основания цилиндра 3, высота 4. Найдите объём. Ответ укажите как коэффициент перед $\\pi$.",
  answer: { kind: "numeric", value: 36, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$V = \\pi r^2 h$." },
    { level: 2, title: "План", body: "$\\pi \\cdot 9 \\cdot 4$." },
    { level: 3, title: "Разбор", body: "$36\\pi$; коэффициент = 36." },
  ],
  solution: [
    "$V = \\pi \\cdot 9 \\cdot 4 = 36\\pi$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-cone-volume",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Конус: объём",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Радиус основания конуса 6, высота 5. Найдите объём. Ответ — коэффициент перед $\\pi$.",
  answer: { kind: "numeric", value: 60, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$V = \\dfrac{1}{3}\\pi r^2 h$." },
    { level: 2, title: "План", body: "$(36 \\cdot 5)/3 = 60$." },
    { level: 3, title: "Разбор", body: "$60\\pi$; коэффициент = 60." },
  ],
  solution: [
    "$V = (1/3) \\pi \\cdot 36 \\cdot 5 = 60\\pi$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-sphere-volume",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Шар: объём",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Радиус шара 3. Найдите объём. Ответ — коэффициент перед $\\pi$.",
  answer: { kind: "numeric", value: 36, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$V = \\dfrac{4}{3}\\pi r^3$." },
    { level: 2, title: "План", body: "$(4 \\cdot 27)/3 = 36$." },
    { level: 3, title: "Разбор", body: "$V = 36\\pi$; коэффициент = 36." },
  ],
  solution: [
    "$V = (4/3)\\pi \\cdot 27 = 36\\pi$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-sphere-surface",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Шар: площадь поверхности",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Радиус шара равен 2. Найдите площадь поверхности. Ответ — коэффициент перед $\\pi$.",
  answer: { kind: "numeric", value: 16, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S = 4\\pi r^2$." },
    { level: 2, title: "План", body: "$4 \\cdot 4 = 16$." },
    { level: 3, title: "Разбор", body: "$16\\pi$." },
  ],
  solution: [
    "$S = 4\\pi \\cdot 4 = 16\\pi$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-cylinder-surface",
  topic: "geometry",
  examNumber: 3,
  examLevel: "профиль",
  subtopic: "Цилиндр: площадь боковой поверхности",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Радиус цилиндра 3, высота 5. Найдите площадь боковой поверхности. Ответ — коэффициент перед $\\pi$.",
  answer: { kind: "numeric", value: 30, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$S_{\\text{бок}} = 2\\pi r h$." },
    { level: 2, title: "План", body: "$2 \\cdot 3 \\cdot 5 = 30$." },
    { level: 3, title: "Разбор", body: "$30\\pi$." },
  ],
  solution: [
    "$S_{\\text{бок}} = 2\\pi \\cdot 3 \\cdot 5 = 30\\pi$.",
  ],
  relatedHandbookTopics: ["hb-geometry-stereometry"],
},
{
  id: "geom-vec-length",
  topic: "geometry",
  examNumber: 2,
  examLevel: "профиль",
  subtopic: "Длина вектора",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите длину вектора $\\vec a = (3; 4)$.",
  answer: { kind: "numeric", value: 5, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$|\\vec a| = \\sqrt{a_x^2 + a_y^2}$." },
    { level: 2, title: "План", body: "$\\sqrt{9 + 16}$." },
    { level: 3, title: "Разбор", body: "$|\\vec a| = \\sqrt{25} = 5$." },
  ],
  solution: [
    "$|\\vec a| = \\sqrt{9+16} = 5$.",
  ],
  relatedHandbookTopics: ["hb-geometry-vectors"],
},
{
  id: "geom-vec-dot",
  topic: "geometry",
  examNumber: 2,
  examLevel: "профиль",
  subtopic: "Скалярное произведение",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите скалярное произведение $\\vec a \\cdot \\vec b$, если $\\vec a = (1; 2)$, $\\vec b = (3; 4)$.",
  answer: { kind: "numeric", value: 11, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$\\vec a \\cdot \\vec b = a_x b_x + a_y b_y$." },
    { level: 2, title: "План", body: "$1 \\cdot 3 + 2 \\cdot 4$." },
    { level: 3, title: "Разбор", body: "$3 + 8 = 11$." },
  ],
  solution: [
    "$\\vec a \\cdot \\vec b = 3 + 8 = 11$.",
  ],
  relatedHandbookTopics: ["hb-geometry-vectors"],
},
{
  id: "geom-vec-angle-cos",
  topic: "geometry",
  examNumber: 2,
  examLevel: "профиль",
  subtopic: "Угол между векторами",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите косинус угла между векторами $\\vec a = (1; 0)$ и $\\vec b = (1; 1)$. Ответ округлите до сотых.",
  answer: { kind: "numeric", value: 0.71, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$\\cos \\varphi = \\dfrac{\\vec a \\cdot \\vec b}{|\\vec a||\\vec b|}$." },
    { level: 2, title: "План", body: "$\\vec a \\cdot \\vec b = 1$, $|\\vec a| = 1$, $|\\vec b| = \\sqrt 2$." },
    { level: 3, title: "Разбор", body: "$\\cos \\varphi = 1/\\sqrt 2 \\approx 0{,}71$." },
  ],
  solution: [
    "$\\cos \\varphi = 1/\\sqrt 2 \\approx 0{,}71$.",
  ],
  relatedHandbookTopics: ["hb-geometry-vectors"],
},
{
  id: "geom-vec-perp",
  topic: "geometry",
  examNumber: 2,
  examLevel: "профиль",
  subtopic: "Перпендикулярность",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "При каком $m$ векторы $\\vec a = (2; m)$ и $\\vec b = (3; 6)$ перпендикулярны?",
  answer: { kind: "numeric", value: -1, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Перпендикулярность: скалярное произведение равно 0." },
    { level: 2, title: "План", body: "$2 \\cdot 3 + m \\cdot 6 = 0$." },
    { level: 3, title: "Разбор", body: "$6 + 6m = 0$, $m = -1$." },
  ],
  solution: [
    "$6 + 6m = 0$, $m = -1$.",
  ],
  relatedHandbookTopics: ["hb-geometry-vectors"],
},
{
  id: "geom-rhombus-side",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Ромб",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Диагонали ромба равны 6 и 8. Найдите его сторону.",
  answer: { kind: "numeric", value: 5, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Диагонали в ромбе перпендикулярны и делят друг друга пополам." },
    { level: 2, title: "План", body: "Половинки: 3 и 4 — катеты прямоугольного треугольника." },
    { level: 3, title: "Разбор", body: "$a = \\sqrt{3^2 + 4^2} = 5$." },
  ],
  solution: [
    "Половины диагоналей: 3 и 4.",
    "$a = \\sqrt{9+16} = 5$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
{
  id: "geom-circumscribed-right",
  topic: "geometry",
  examNumber: 1,
  examLevel: "профиль",
  subtopic: "Описанная окружность",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В прямоугольном треугольнике гипотенуза равна 10. Найдите радиус описанной окружности.",
  answer: { kind: "numeric", value: 5, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "В прямоугольном треугольнике центр описанной окружности — середина гипотенузы." },
    { level: 2, title: "План", body: "$R = c/2$." },
    { level: 3, title: "Разбор", body: "$R = 10/2 = 5$." },
  ],
  solution: [
    "$R = c/2 = 5$.",
  ],
  relatedHandbookTopics: ["hb-geometry-planimetry"],
},
];
