import type { Task } from "../types";

/**
 * Задачи на теорию вероятностей (ЕГЭ профиль 2025: №4 и №5).
 * Сгенерировано через scripts/gen_tasks.py — не правьте файл вручную.
 */

export const probabilityTasks: Task[] = [
{
  id: "prob-classical-coin-2",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Монету подбрасывают два раза. Найдите вероятность того, что орёл выпадет ровно один раз.",
  answer: { kind: "numeric", value: 0.5, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Перечислите все элементарные исходы двух подбрасываний — их 4." },
    { level: 2, title: "План", body: "Найдите количество исходов, в которых ровно один орёл, и поделите на общее число исходов: $P=\\dfrac{m}{n}$." },
    { level: 3, title: "Разбор", body: "Исходы: ОО, ОР, РО, РР. Ровно один орёл в исходах ОР и РО — два благоприятных. $P=\\dfrac{2}{4}=0{,}5$." },
  ],
  solution: [
    "Всего исходов: $2 \\cdot 2 = 4$ — это ОО, ОР, РО, РР.",
    "Благоприятных (ровно один орёл): ОР, РО — два исхода.",
    "$P = \\dfrac{2}{4} = 0{,}5$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-classical-tickets",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "На экзамене 25 билетов, Сергей не выучил 5 из них. Найдите вероятность того, что ему попадётся выученный билет.",
  answer: { kind: "numeric", value: 0.8, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сколько билетов он выучил?" },
    { level: 2, title: "План", body: "Поделите количество выученных билетов на общее число." },
    { level: 3, title: "Разбор", body: "$P=\\dfrac{25-5}{25}=\\dfrac{20}{25}=0{,}8$." },
  ],
  solution: [
    "Выученных билетов: $25-5=20$.",
    "$P=\\dfrac{20}{25}=0{,}8$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-olympiad-rooms",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "На олимпиаде по математике 550 участников разместили в четырёх аудиториях. В первых трёх удалось разместить по 110 человек, оставшихся перевели в запасную аудиторию. Найдите вероятность того, что случайно выбранный участник писал олимпиаду в запасной аудитории.",
  answer: { kind: "numeric", value: 0.4, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сколько человек село в первые три аудитории?" },
    { level: 2, title: "План", body: "Найдите число человек в запасной аудитории и поделите на 550." },
    { level: 3, title: "Разбор", body: "В первых трёх: $3 \\cdot 110 = 330$. В запасной: $550-330=220$. $P=\\dfrac{220}{550}=0{,}4$." },
  ],
  solution: [
    "В первых трёх: $3 \\cdot 110 = 330$.",
    "В запасной: $550-330=220$.",
    "$P=\\dfrac{220}{550}=0{,}4$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-union",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Объединение и пересечение событий",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вероятность того, что новый компьютер прослужит больше года, равна $0{,}97$. Вероятность того, что он прослужит больше двух лет, равна $0{,}89$. Найдите вероятность того, что компьютер прослужит больше года, но меньше двух лет.",
  answer: { kind: "numeric", value: 0.08, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Если $A$ — «больше года», а $B$ — «больше двух лет», то $B \\subset A$." },
    { level: 2, title: "План", body: "Искомое событие = $A \\setminus B$. $P(A \\setminus B) = P(A) - P(B)$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}97 - 0{,}89 = 0{,}08$." },
  ],
  solution: [
    "Событие «больше двух лет» содержится в «больше года».",
    "$P = 0{,}97 - 0{,}89 = 0{,}08$.",
  ],
  relatedHandbookTopics: ["hb-probability-union"],
},
{
  id: "prob-bernoulli-shooter",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула Бернулли",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вероятность поражения мишени при одном выстреле равна $0{,}8$. Стрелок производит 3 независимых выстрела. Найдите вероятность того, что мишень будет поражена ровно два раза.",
  answer: { kind: "numeric", value: 0.384, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Это схема Бернулли: $n=3$, $p=0{,}8$, $k=2$." },
    { level: 2, title: "План", body: "$P_n(k) = C_n^k p^k (1-p)^{n-k}$." },
    { level: 3, title: "Разбор", body: "$C_3^2 = 3$. $P = 3 \\cdot 0{,}8^2 \\cdot 0{,}2 = 0{,}384$." },
  ],
  solution: [
    "$C_3^2=3$, $0{,}8^2 = 0{,}64$, $0{,}64 \\cdot 0{,}2 = 0{,}128$.",
    "$P = 3 \\cdot 0{,}128 = 0{,}384$.",
  ],
  relatedHandbookTopics: ["hb-probability-bernoulli"],
},
{
  id: "prob-coin-4-times",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула Бернулли",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Монету бросают 4 раза. Найдите вероятность того, что орёл выпадет ровно 2 раза.",
  answer: { kind: "numeric", value: 0.375, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "$n=4$, $k=2$, $p=0{,}5$." },
    { level: 2, title: "План", body: "$P = C_4^2 \\cdot p^k \\cdot (1-p)^{n-k}$." },
    { level: 3, title: "Разбор", body: "$C_4^2 = 6$. $P = 6 \\cdot 0{,}5^4 = 0{,}375$." },
  ],
  solution: [
    "$C_4^2 = 6$, $0{,}5^4 = 0{,}0625$.",
    "$P = 6 \\cdot 0{,}0625 = 0{,}375$.",
  ],
  relatedHandbookTopics: ["hb-probability-bernoulli"],
},
{
  id: "prob-total-factory",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула полной вероятности",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В магазине поступают батарейки от двух поставщиков: 60% от первого и 40% от второго. У первого брак — 2%, у второго — 5%. Найдите вероятность того, что случайно выбранная батарейка окажется бракованной.",
  answer: { kind: "numeric", value: 0.032, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "$H_1$ — от первого, $H_2$ — от второго." },
    { level: 2, title: "План", body: "$P(A) = P(H_1)P(A|H_1) + P(H_2)P(A|H_2)$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}6 \\cdot 0{,}02 + 0{,}4 \\cdot 0{,}05 = 0{,}032$." },
  ],
  solution: [
    "$P(H_1)=0{,}6$, $P(H_2)=0{,}4$.",
    "$P=0{,}6 \\cdot 0{,}02 + 0{,}4 \\cdot 0{,}05 = 0{,}032$.",
  ],
  relatedHandbookTopics: ["hb-probability-total"],
},
{
  id: "prob-conditional-cards",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Условная вероятность",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вероятность того, что батарейка бракованная, равна $0{,}06$. Покупатель берёт упаковку из 2 батареек. Найдите вероятность того, что обе батарейки исправны.",
  answer: { kind: "numeric", value: 0.8836, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Вероятность исправности одной батарейки?" },
    { level: 2, title: "План", body: "Если батарейки независимы, вероятности перемножаются." },
    { level: 3, title: "Разбор", body: "$P(\\text{исправна}) = 0{,}94$. $P(\\text{обе}) = 0{,}94^2 = 0{,}8836$." },
  ],
  solution: [
    "$P(\\text{исправна}) = 1 - 0{,}06 = 0{,}94$.",
    "$P = 0{,}94^2 = 0{,}8836$.",
  ],
  relatedHandbookTopics: ["hb-probability-union", "hb-probability-conditional"],
},
{
  id: "prob-geometric-segment",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Геометрическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "На отрезке $[0;\\,5]$ случайным образом выбирается точка. Найдите вероятность того, что её координата больше 3.",
  answer: { kind: "numeric", value: 0.4, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Какая часть отрезка удовлетворяет условию?" },
    { level: 2, title: "План", body: "$P = \\dfrac{\\text{длина}(A)}{\\text{длина}(\\Omega)}$." },
    { level: 3, title: "Разбор", body: "Длина благоприятной области $[3;5]$ равна 2, всей $[0;5]$ — 5. $P = 2/5 = 0{,}4$." },
  ],
  solution: [
    "Благоприятная область — отрезок $[3;5]$ длины 2.",
    "$P = 2/5 = 0{,}4$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-classical-dice-six",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Игральную кость бросают один раз. Найдите вероятность того, что выпадет более 4 очков.",
  answer: { kind: "numeric", value: 0.3333333333333333, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Какие из 6 граней дают «более 4»?" },
    { level: 2, title: "План", body: "Поделите количество благоприятных на 6." },
    { level: 3, title: "Разбор", body: "Благоприятны 5 и 6: $P = 2/6 = 1/3 \\approx 0{,}33$." },
  ],
  solution: [
    "Благоприятных исходов: 2 (5 и 6 очков).",
    "$P = 2/6 = 1/3 \\approx 0{,}33$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-bernoulli-test-questions",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула Бернулли",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Стрелок попадает в мишень с вероятностью $0{,}9$. Он делает 5 независимых выстрелов. Найдите вероятность того, что он попадёт ровно 4 раза.",
  answer: { kind: "numeric", value: 0.32805, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Схема Бернулли: $n=5$, $p=0{,}9$, $k=4$." },
    { level: 2, title: "План", body: "$P_n(k) = C_n^k p^k (1-p)^{n-k}$." },
    { level: 3, title: "Разбор", body: "$C_5^4 = 5$. $P = 5 \\cdot 0{,}9^4 \\cdot 0{,}1 = 0{,}32805$." },
  ],
  solution: [
    "$C_5^4 = 5$, $0{,}9^4 = 0{,}6561$.",
    "$P = 5 \\cdot 0{,}6561 \\cdot 0{,}1 = 0{,}32805$.",
  ],
  relatedHandbookTopics: ["hb-probability-bernoulli"],
},
{
  id: "prob-total-disease",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула полной вероятности",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В первой коробке 3 синих и 7 красных шаров. Во второй — 6 синих и 4 красных. Подбрасывают честную монету: при «орле» шар достают из первой коробки, при «решке» — из второй. Найдите вероятность того, что вынутый шар синий.",
  answer: { kind: "numeric", value: 0.45, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "$H_1$ — выбрана 1-я коробка, $H_2$ — 2-я." },
    { level: 2, title: "План", body: "$P = P(H_1)P(C|H_1) + P(H_2)P(C|H_2)$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}5 \\cdot 0{,}3 + 0{,}5 \\cdot 0{,}6 = 0{,}45$." },
  ],
  solution: [
    "$P(C|H_1) = 3/10 = 0{,}3$, $P(C|H_2) = 6/10 = 0{,}6$.",
    "$P = 0{,}5(0{,}3 + 0{,}6) = 0{,}45$.",
  ],
  relatedHandbookTopics: ["hb-probability-total"],
},
{
  id: "prob-classical-red-ball",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В урне 8 белых и 12 чёрных шаров. Наугад вытягивают один шар. Найдите вероятность того, что он белый.",
  answer: { kind: "numeric", value: 0.4, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Общее число шаров — сумма белых и чёрных." },
    { level: 2, title: "План", body: "$P = \\dfrac{\\text{белых}}{\\text{всего}}$." },
    { level: 3, title: "Разбор", body: "$P = 8/(8+12) = 8/20 = 0{,}4$." },
  ],
  solution: [
    "Всего шаров: $8+12=20$.",
    "$P = 8/20 = 0{,}4$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-classical-ball-not-red",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В корзине 4 красных, 3 жёлтых и 3 зелёных яблока. Случайно берут одно. Найдите вероятность того, что оно не красное.",
  answer: { kind: "numeric", value: 0.6, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сколько яблок не красные?" },
    { level: 2, title: "План", body: "Поделите на общее число." },
    { level: 3, title: "Разбор", body: "$P = (3+3)/10 = 0{,}6$. Или: $P = 1 - 4/10 = 0{,}6$." },
  ],
  solution: [
    "Некрасных: $3+3 = 6$.",
    "$P = 6/10 = 0{,}6$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-classical-weekday",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В случайном эксперименте из колоды в 36 карт берут одну. Найдите вероятность того, что это туз.",
  answer: { kind: "numeric", value: 0.1111111111111111, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сколько тузов в колоде 36 карт?" },
    { level: 2, title: "План", body: "Поделите количество тузов на 36." },
    { level: 3, title: "Разбор", body: "Тузов — 4. $P = 4/36 = 1/9 \\approx 0{,}11$." },
  ],
  solution: [
    "Тузов в колоде 4.",
    "$P = 4/36 = 1/9 \\approx 0{,}11$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-classical-dice-sum",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Бросают две игральные кости. Найдите вероятность того, что сумма выпавших очков равна 7.",
  answer: { kind: "numeric", value: 0.16666666666666666, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сколько всего исходов при броске двух костей?" },
    { level: 2, title: "План", body: "Сколько пар даёт сумму 7? Выпишите их." },
    { level: 3, title: "Разбор", body: "Всего $6 \\cdot 6 = 36$ исходов. Сумма 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) — 6 исходов. $P = 6/36 = 1/6$." },
  ],
  solution: [
    "Всего исходов: $6 \\times 6 = 36$.",
    "Сумма 7 достигается в 6 парах.",
    "$P = 6/36 \\approx 0{,}167$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-classical-team",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В классе 12 девочек и 13 мальчиков. Для дежурства случайно выбирают одного ученика. Найдите вероятность того, что это мальчик.",
  answer: { kind: "numeric", value: 0.52, tolerance: 0.005 },
  hints: [
    { level: 1, title: "Подсказка", body: "Поделите число мальчиков на общее число учеников." },
    { level: 2, title: "План", body: "$P = \\dfrac{13}{12+13}$." },
    { level: 3, title: "Разбор", body: "$P = 13/25 = 0{,}52$." },
  ],
  solution: [
    "Всего $12+13 = 25$ учеников.",
    "$P = 13/25 = 0{,}52$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-complement-shooter",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Противоположное событие",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вероятность попадания при одном выстреле равна $0{,}7$. Стрелок стреляет 3 раза. Найдите вероятность того, что он попадёт хотя бы один раз.",
  answer: { kind: "numeric", value: 0.973, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Проще посчитать вероятность противоположного события — ни разу не попасть." },
    { level: 2, title: "План", body: "$P(\\text{ни одного}) = (1-p)^n = 0{,}3^3$." },
    { level: 3, title: "Разбор", body: "$P(\\text{ни одного}) = 0{,}027$. $P(\\text{хотя бы одно}) = 1 - 0{,}027 = 0{,}973$." },
  ],
  solution: [
    "$P(\\text{ни одного}) = 0{,}3^3 = 0{,}027$.",
    "$P(\\text{хотя бы одно}) = 1 - 0{,}027 = 0{,}973$.",
  ],
  relatedHandbookTopics: ["hb-probability-union"],
},
{
  id: "prob-complement-two-weeks",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Противоположное событие",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вероятность того, что в магазине закончится нужный товар за неделю, равна $0{,}18$. Найдите вероятность того, что товар не закончится.",
  answer: { kind: "numeric", value: 0.82, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Это противоположное событие." },
    { level: 2, title: "План", body: "$P(\\bar A) = 1 - P(A)$." },
    { level: 3, title: "Разбор", body: "$P = 1 - 0{,}18 = 0{,}82$." },
  ],
  solution: [
    "$P(\\bar A) = 1 - 0{,}18 = 0{,}82$.",
  ],
  relatedHandbookTopics: ["hb-probability-union"],
},
{
  id: "prob-indep-two-events",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Независимые события",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Две независимые лампы работают. Вероятность того, что за год не перегорит первая, равна $0{,}9$, а вторая — $0{,}8$. Найдите вероятность того, что за год не перегорит ни одна из них.",
  answer: { kind: "numeric", value: 0.72, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "События независимы — вероятности перемножаются." },
    { level: 2, title: "План", body: "$P(A \\cap B) = P(A) \\cdot P(B)$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}9 \\cdot 0{,}8 = 0{,}72$." },
  ],
  solution: [
    "$P = 0{,}9 \\cdot 0{,}8 = 0{,}72$.",
  ],
  relatedHandbookTopics: ["hb-probability-union", "hb-probability-conditional"],
},
{
  id: "prob-sequential-defect",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Независимые события",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "На фабрике из 100 деталей 5 бракованных. Контролёр наугад берёт одну деталь, проверяет и кладёт обратно, затем берёт ещё одну. Найдите вероятность того, что обе окажутся бракованными.",
  answer: { kind: "numeric", value: 0.0025, tolerance: 1e-05 },
  hints: [
    { level: 1, title: "Подсказка", body: "Деталь возвращают — испытания независимы." },
    { level: 2, title: "План", body: "$P = P(\\text{брак})^2$." },
    { level: 3, title: "Разбор", body: "$P(\\text{брак}) = 5/100 = 0{,}05$. $P(\\text{оба брак}) = 0{,}05^2 = 0{,}0025$." },
  ],
  solution: [
    "$P(\\text{брак}) = 0{,}05$.",
    "$P = 0{,}05^2 = 0{,}0025$.",
  ],
  relatedHandbookTopics: ["hb-probability-union", "hb-probability-conditional"],
},
{
  id: "prob-bernoulli-exam",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула Бернулли",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В лотерее выигрышный билет встречается с вероятностью $0{,}2$. Покупают 4 билета. Найдите вероятность того, что ровно 1 из них выигрышный.",
  answer: { kind: "numeric", value: 0.4096, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Схема Бернулли: $n=4$, $k=1$, $p=0{,}2$." },
    { level: 2, title: "План", body: "$P_n(k) = C_n^k p^k (1-p)^{n-k}$." },
    { level: 3, title: "Разбор", body: "$C_4^1 = 4$. $P = 4 \\cdot 0{,}2 \\cdot 0{,}8^3 = 4 \\cdot 0{,}2 \\cdot 0{,}512 = 0{,}4096$." },
  ],
  solution: [
    "$C_4^1 = 4$, $0{,}8^3 = 0{,}512$.",
    "$P = 4 \\cdot 0{,}2 \\cdot 0{,}512 = 0{,}4096$.",
  ],
  relatedHandbookTopics: ["hb-probability-bernoulli"],
},
{
  id: "prob-bernoulli-exactly-zero",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула Бернулли",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Всхожесть семян равна $0{,}9$. Посадили 5 семян. Найдите вероятность того, что ни одно из них не взойдёт.",
  answer: { kind: "numeric", value: 1e-05, tolerance: 1e-06 },
  hints: [
    { level: 1, title: "Подсказка", body: "$P(\\text{не взошло одно}) = 1 - 0{,}9 = 0{,}1$." },
    { level: 2, title: "План", body: "Независимые события — вероятности перемножаются." },
    { level: 3, title: "Разбор", body: "$P = 0{,}1^5 = 0{,}00001$." },
  ],
  solution: [
    "$P(\\text{не взойдёт одно}) = 0{,}1$.",
    "$P = 0{,}1^5 = 10^{-5}$.",
  ],
  relatedHandbookTopics: ["hb-probability-bernoulli"],
},
{
  id: "prob-union-soccer",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Объединение событий",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В магазине доля бракованных лампочек равна $0{,}04$, доля лампочек с пониженной яркостью — $0{,}01$. Некоторые лампочки имеют обе проблемы: $0{,}005$. Найдите вероятность того, что случайно выбранная лампочка имеет хотя бы один дефект.",
  answer: { kind: "numeric", value: 0.045, tolerance: 0.0005 },
  hints: [
    { level: 1, title: "Подсказка", body: "Формула объединения: $P(A \\cup B) = P(A) + P(B) - P(A \\cap B)$." },
    { level: 2, title: "План", body: "Подставьте: $A$ — брак, $B$ — пониженная яркость." },
    { level: 3, title: "Разбор", body: "$P = 0{,}04 + 0{,}01 - 0{,}005 = 0{,}045$." },
  ],
  solution: [
    "$P(A \\cup B) = 0{,}04 + 0{,}01 - 0{,}005 = 0{,}045$.",
  ],
  relatedHandbookTopics: ["hb-probability-union"],
},
{
  id: "prob-total-three-factories",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула полной вероятности",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Комплектующие поступают с трёх заводов: 50%, 30% и 20%. Брак: 1%, 2% и 5% соответственно. Найдите вероятность того, что случайная деталь бракованная.",
  answer: { kind: "numeric", value: 0.021, tolerance: 0.0005 },
  hints: [
    { level: 1, title: "Подсказка", body: "Формула полной вероятности с тремя гипотезами." },
    { level: 2, title: "План", body: "$P = 0{,}5 \\cdot 0{,}01 + 0{,}3 \\cdot 0{,}02 + 0{,}2 \\cdot 0{,}05$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}005 + 0{,}006 + 0{,}01 = 0{,}021$." },
  ],
  solution: [
    "$P = 0{,}5 \\cdot 0{,}01 + 0{,}3 \\cdot 0{,}02 + 0{,}2 \\cdot 0{,}05$.",
    "$= 0{,}005 + 0{,}006 + 0{,}010 = 0{,}021$.",
  ],
  relatedHandbookTopics: ["hb-probability-total"],
},
{
  id: "prob-conditional-jar",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Условная вероятность",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В урне 5 белых и 5 чёрных шаров. Последовательно вытягивают 2 шара без возвращения. Найдите вероятность того, что оба белых.",
  answer: { kind: "numeric", value: 0.2222222222222222, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "$P(A \\cap B) = P(A) \\cdot P(B \\mid A)$." },
    { level: 2, title: "План", body: "После первого белого в урне осталось 4 белых из 9." },
    { level: 3, title: "Разбор", body: "$P = \\dfrac{5}{10} \\cdot \\dfrac{4}{9} = \\dfrac{20}{90} = \\dfrac{2}{9} \\approx 0{,}22$." },
  ],
  solution: [
    "$P = (5/10) \\cdot (4/9) = 20/90 = 2/9 \\approx 0{,}22$.",
  ],
  relatedHandbookTopics: ["hb-probability-conditional"],
},
{
  id: "prob-geometric-square",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Геометрическая вероятность",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В квадрате со стороной 1 наугад выбирают точку. Найдите вероятность того, что она окажется внутри вписанного круга.",
  answer: { kind: "numeric", value: 0.7853981625, tolerance: 0.005 },
  hints: [
    { level: 1, title: "Подсказка", body: "Вписанная окружность имеет радиус $1/2$." },
    { level: 2, title: "План", body: "$P = \\dfrac{S_{\\text{круга}}}{S_{\\text{квадрата}}}$." },
    { level: 3, title: "Разбор", body: "$S_{\\text{круга}} = \\pi/4$, $S_{\\text{квадрата}} = 1$. $P = \\pi/4 \\approx 0{,}785$." },
  ],
  solution: [
    "$S_{\\text{круга}} = \\pi r^2 = \\pi/4$.",
    "$P = (\\pi/4)/1 = \\pi/4 \\approx 0{,}785$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical"],
},
{
  id: "prob-two-red-shots",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Независимые события",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Иван делает 2 выстрела по мишени. Вероятность попадания равна $0{,}6$ при каждом выстреле. Найдите вероятность того, что он попадёт ровно в 1 раз.",
  answer: { kind: "numeric", value: 0.48, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "«Попал + промазал» или «промазал + попал»." },
    { level: 2, title: "План", body: "$P = 2 \\cdot p \\cdot (1-p)$ (по формуле Бернулли)." },
    { level: 3, title: "Разбор", body: "$P = 2 \\cdot 0{,}6 \\cdot 0{,}4 = 0{,}48$." },
  ],
  solution: [
    "$P = 2 \\cdot 0{,}6 \\cdot 0{,}4 = 0{,}48$.",
  ],
  relatedHandbookTopics: ["hb-probability-bernoulli"],
},
{
  id: "prob-bayes-test",
  topic: "probability",
  examNumber: 5,
  examLevel: "профиль",
  subtopic: "Формула Байеса",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Из двух автоматов 1-й производит 70% продукции, 2-й — 30%. Брак у 1-го — 1%, у 2-го — 4%. Найдите вероятность того, что случайно выбранная деталь бракованная.",
  answer: { kind: "numeric", value: 0.019, tolerance: 0.0005 },
  hints: [
    { level: 1, title: "Подсказка", body: "Формула полной вероятности." },
    { level: 2, title: "План", body: "$P = 0{,}7 \\cdot 0{,}01 + 0{,}3 \\cdot 0{,}04$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}007 + 0{,}012 = 0{,}019$." },
  ],
  solution: [
    "$P = 0{,}007 + 0{,}012 = 0{,}019$.",
  ],
  relatedHandbookTopics: ["hb-probability-total"],
},
{
  id: "prob-hospital-boys",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Вероятность рождения мальчика равна $0{,}512$. В некотором роддоме в понедельник родились 2 ребёнка. Найдите вероятность того, что оба мальчики.",
  answer: { kind: "numeric", value: 0.262144, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "События независимы — перемножаем вероятности." },
    { level: 2, title: "План", body: "$P = 0{,}512 \\cdot 0{,}512$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}512^2 \\approx 0{,}262$." },
  ],
  solution: [
    "$P = 0{,}512^2 \\approx 0{,}262$.",
  ],
  relatedHandbookTopics: ["hb-probability-classical", "hb-probability-union"],
},
{
  id: "prob-taxi-free",
  topic: "probability",
  examNumber: 4,
  examLevel: "профиль",
  subtopic: "Классическая вероятность",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Пассажир заказал такси. Вероятность того, что к нему приедет белая машина, равна $0{,}25$. А вероятность, что не белая — соответственно, $0{,}75$. Найдите вероятность того, что приедет не белое такси.",
  answer: { kind: "numeric", value: 0.75, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "$P(\\bar A) = 1 - P(A)$." },
    { level: 2, title: "План", body: "$P = 1 - 0{,}25$." },
    { level: 3, title: "Разбор", body: "$P = 0{,}75$." },
  ],
  solution: [
    "$P = 1 - 0{,}25 = 0{,}75$.",
  ],
  relatedHandbookTopics: ["hb-probability-union"],
},
];
