import type { Task } from "../types";

/**
 * Задачи на статистику (ЕГЭ база №9 / профиль №11).
 * Сгенерировано через scripts/gen_tasks.py — не правьте файл вручную.
 */

export const statisticsTasks: Task[] = [
{
  id: "stat-mean",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Среднее арифметическое",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите среднее арифметическое чисел: 1, 5, 7, 12, 15.",
  answer: { kind: "numeric", value: 8, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сумма всех чисел, делённая на их количество." },
    { level: 2, title: "План", body: "$1+5+7+12+15 = 40$." },
    { level: 3, title: "Разбор", body: "$\\bar{x} = 40/5 = 8$." },
  ],
  solution: [
    "Сумма: 40. Количество: 5.",
    "$\\bar{x} = 40/5 = 8$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-median",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Медиана",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите медиану ряда чисел: 2, 8, 11, 4, 6, 15, 3.",
  answer: { kind: "numeric", value: 6, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Медиана — середина упорядоченного ряда." },
    { level: 2, title: "План", body: "Упорядочьте: 2, 3, 4, 6, 8, 11, 15." },
    { level: 3, title: "Разбор", body: "В ряду 7 чисел, медиана — четвёртое: 6." },
  ],
  solution: [
    "Упорядоченный ряд: 2, 3, 4, 6, 8, 11, 15.",
    "Медиана — 4-й элемент: 6.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-range",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Размах",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите размах ряда чисел: 12, 5, 18, 3, 22, 11.",
  answer: { kind: "numeric", value: 19, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Размах — разность наибольшего и наименьшего." },
    { level: 2, title: "План", body: "max = 22, min = 3." },
    { level: 3, title: "Разбор", body: "$R = 22 - 3 = 19$." },
  ],
  solution: [
    "max = 22, min = 3.",
    "$R = 19$.",
  ],
  relatedHandbookTopics: ["hb-statistics-spread"],
},
{
  id: "stat-mean-median-mismatch",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Средние величины",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В наборе 9 чисел медиана равна 5, а среднее арифметическое равно 6. Если из набора убрать число 5, то медиана нового набора будет равна 4. Чему равно среднее арифметическое нового набора?",
  answer: { kind: "numeric", value: 6.125, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сумма исходных 9 чисел = $9 \\cdot 6 = 54$." },
    { level: 2, title: "План", body: "После удаления числа 5 сумма = 49, чисел 8." },
    { level: 3, title: "Разбор", body: "$\\bar{x} = 49/8 = 6{,}125$." },
  ],
  solution: [
    "$9 \\cdot 6 = 54$.",
    "$54 - 5 = 49$.",
    "$49/8 = 6{,}125$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-frequency",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Частота и доля",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "За контрольную по алгебре в классе из 25 учеников «5» получили 4, «4» получили 12, «3» получили 7, остальные получили «2». Какую долю от общего числа учеников составляют двоечники? Дайте ответ в виде десятичной дроби.",
  answer: { kind: "numeric", value: 0.08, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сколько двоечников? $25 - 4 - 12 - 7 = 2$." },
    { level: 2, title: "План", body: "Доля = количество / общее число." },
    { level: 3, title: "Разбор", body: "$\\dfrac{2}{25} = 0{,}08$." },
  ],
  solution: [
    "Двоечников: $25-4-12-7 = 2$.",
    "$2/25 = 0{,}08$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-graph-temperature",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Чтение графиков",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В понедельник температура была 5 °C, во вторник 7 °C, в среду 4 °C, в четверг 6 °C, в пятницу 3 °C. Найдите среднюю температуру за эти 5 дней.",
  answer: { kind: "numeric", value: 5, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сложите все 5 значений." },
    { level: 2, title: "План", body: "Сумму поделите на 5." },
    { level: 3, title: "Разбор", body: "$5+7+4+6+3 = 25$. $25/5 = 5$." },
  ],
  solution: [
    "Сумма: 25.",
    "Средняя: $25/5 = 5$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages", "hb-statistics-graphs"],
},
{
  id: "stat-mode",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Мода",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите моду ряда чисел: 3, 5, 5, 7, 8, 5, 9, 3.",
  answer: { kind: "numeric", value: 5, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Мода — самое частое число." },
    { level: 2, title: "План", body: "Подсчитайте количество каждого числа." },
    { level: 3, title: "Разбор", body: "5 встречается 3 раза — больше всех. Мода = 5." },
  ],
  solution: [
    "3 (×2), 5 (×3), 7, 8, 9.",
    "Мода = 5.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-mean-6",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Среднее арифметическое",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите среднее арифметическое чисел 10, 14, 18, 22, 26, 30.",
  answer: { kind: "numeric", value: 20, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сложить и поделить." },
    { level: 2, title: "План", body: "Сумма арифметической прогрессии = 6 слагаемых, крайние 10 и 30." },
    { level: 3, title: "Разбор", body: "Сумма = $6 \\cdot (10+30)/2 = 120$. Среднее = $120/6 = 20$." },
  ],
  solution: [
    "Сумма = $(10+30) \\cdot 6/2 = 120$.",
    "Среднее = $120/6 = 20$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-weighted-mean",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Взвешенное среднее",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Студент получил оценки: по математике — 5, по физике — 4, по химии — 3. Весовые коэффициенты: 3, 2 и 1 соответственно. Найдите взвешенное среднее.",
  answer: { kind: "numeric", value: 4.333333333333333, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Взвешенное среднее: $\\bar x = \\dfrac{\\sum x_i w_i}{\\sum w_i}$." },
    { level: 2, title: "План", body: "Числитель: $5 \\cdot 3 + 4 \\cdot 2 + 3 \\cdot 1 = 26$." },
    { level: 3, title: "Разбор", body: "Знаменатель: $3+2+1 = 6$. $\\bar x = 26/6 \\approx 4{,}33$." },
  ],
  solution: [
    "Числитель: $15 + 8 + 3 = 26$.",
    "Знаменатель: 6.",
    "$\\bar x = 26/6 \\approx 4{,}33$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-median-even",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Медиана",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите медиану ряда: 2, 4, 5, 7, 8, 10.",
  answer: { kind: "numeric", value: 6, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "В ряду 6 чисел, медиана — среднее двух центральных." },
    { level: 2, title: "План", body: "Центральные: 5 и 7." },
    { level: 3, title: "Разбор", body: "Медиана = $(5+7)/2 = 6$." },
  ],
  solution: [
    "Ряд уже упорядочен.",
    "Центральные: 5 и 7.",
    "Медиана = $(5+7)/2 = 6$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-two-medians",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Медиана",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В наборе 8 чисел после упорядочивания получили: 1, 3, 5, 7, 9, 11, 13, 15. Найдите медиану.",
  answer: { kind: "numeric", value: 8, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Чётное количество — среднее двух центральных." },
    { level: 2, title: "План", body: "Центральные: 4-й и 5-й, то есть 7 и 9." },
    { level: 3, title: "Разбор", body: "$(7+9)/2 = 8$." },
  ],
  solution: [
    "Центральные: 7 и 9.",
    "Медиана = 8.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-range-2",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Размах",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В классе измерили рост учеников (в см): 155, 162, 148, 175, 168, 170, 155. Найдите размах.",
  answer: { kind: "numeric", value: 27, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "max - min." },
    { level: 2, title: "План", body: "max = 175, min = 148." },
    { level: 3, title: "Разбор", body: "$175 - 148 = 27$." },
  ],
  solution: [
    "max = 175, min = 148.",
    "$R = 27$.",
  ],
  relatedHandbookTopics: ["hb-statistics-spread"],
},
{
  id: "stat-variance-simple",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Дисперсия",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите дисперсию ряда: 2, 4, 4, 4, 5, 5, 7, 9. Дайте ответ с точностью до сотых.",
  answer: { kind: "numeric", value: 4, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сначала найдите среднее: $\\bar x = 5$." },
    { level: 2, title: "План", body: "Дисперсия: среднее квадратов отклонений от среднего." },
    { level: 3, title: "Разбор", body: "Отклонения: $(-3)^2, (-1)^2, (-1)^2, (-1)^2, 0^2, 0^2, 2^2, 4^2 = 9,1,1,1,0,0,4,16$. Сумма = 32. $D = 32/8 = 4$." },
  ],
  solution: [
    "$\\bar x = (2+4+4+4+5+5+7+9)/8 = 40/8 = 5$.",
    "Сумма квадратов отклонений: $9+1+1+1+0+0+4+16 = 32$.",
    "$D = 32/8 = 4$.",
  ],
  relatedHandbookTopics: ["hb-statistics-spread"],
},
{
  id: "stat-percentage-sale",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Проценты и доли",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Магазин продал 120 единиц товара, из которых 30 были со скидкой. Какой процент товара был продан со скидкой?",
  answer: { kind: "numeric", value: 25, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Доля * 100%." },
    { level: 2, title: "План", body: "$30/120 \\cdot 100\\%$." },
    { level: 3, title: "Разбор", body: "$30/120 = 0{,}25 = 25\\%$." },
  ],
  solution: [
    "$30/120 = 0{,}25$.",
    "$0{,}25 \\cdot 100\\% = 25\\%$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-bar-chart",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Чтение диаграмм",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "На диаграмме показано количество проданных товаров по дням: пн — 40, вт — 60, ср — 50, чт — 30, пт — 70. Во сколько раз в пятницу продали больше, чем в четверг?",
  answer: { kind: "numeric", value: 2.3333333333333335, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Поделите пятницу на четверг." },
    { level: 2, title: "План", body: "$70/30$." },
    { level: 3, title: "Разбор", body: "$70/30 = 7/3 \\approx 2{,}33$." },
  ],
  solution: [
    "$70/30 = 7/3 \\approx 2{,}33$.",
  ],
  relatedHandbookTopics: ["hb-statistics-graphs"],
},
{
  id: "stat-average-chart",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Чтение диаграмм",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "За 5 дней недели в магазине продали 40, 60, 50, 30, 70 товаров. Найдите среднесуточные продажи.",
  answer: { kind: "numeric", value: 50, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сумма/количество." },
    { level: 2, title: "План", body: "Сумма: $40+60+50+30+70 = 250$." },
    { level: 3, title: "Разбор", body: "Среднесуточная: $250/5 = 50$." },
  ],
  solution: [
    "Сумма = 250.",
    "$250/5 = 50$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-weight-kg",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Среднее",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В группе 10 человек, средний вес 65 кг. Пришёл ещё один человек — суммарный средний вес стал 66 кг. Сколько весил пришедший?",
  answer: { kind: "numeric", value: 76, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Сумма до: $10 \\cdot 65$." },
    { level: 2, title: "План", body: "Сумма после: $11 \\cdot 66$." },
    { level: 3, title: "Разбор", body: "Разница: $726 - 650 = 76$ кг." },
  ],
  solution: [
    "$S_{10} = 650$.",
    "$S_{11} = 726$.",
    "$w = 76$ кг.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-relative-frequency",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Частота и доля",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Проведено 200 бросаний монеты, орёл выпал 107 раз. Найдите относительную частоту выпадения орла. Дайте ответ в виде десятичной дроби.",
  answer: { kind: "numeric", value: 0.535, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Относительная частота = выпадения/всего." },
    { level: 2, title: "План", body: "$107/200$." },
    { level: 3, title: "Разбор", body: "$107/200 = 0{,}535$." },
  ],
  solution: [
    "$107/200 = 0{,}535$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-price-increase",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Проценты",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Цена товара выросла с 450 до 540 рублей. На сколько процентов выросла цена?",
  answer: { kind: "numeric", value: 20, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "$(\\text{новая} - \\text{старая})/\\text{старая} \\cdot 100\\%$." },
    { level: 2, title: "План", body: "$(540 - 450)/450 = 90/450$." },
    { level: 3, title: "Разбор", body: "$90/450 = 0{,}2 = 20\\%$." },
  ],
  solution: [
    "Изменение = $540-450 = 90$.",
    "$90/450 = 0{,}2 = 20\\%$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-student-scores",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Частота",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В школе 400 учеников. На ЕГЭ 120 получили от 80 баллов и выше. Какую долю составляют высокобалльники?",
  answer: { kind: "numeric", value: 0.3, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Доля = часть/целое." },
    { level: 2, title: "План", body: "$120/400$." },
    { level: 3, title: "Разбор", body: "$120/400 = 0{,}3$." },
  ],
  solution: [
    "$120/400 = 0{,}3$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-pie-slice",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Чтение диаграмм",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В круговой диаграмме сектору 'Математика' соответствует угол 144°. Какой процент всех учеников выбрали математику?",
  answer: { kind: "numeric", value: 40, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Полный круг — 360°, что равно 100%." },
    { level: 2, title: "План", body: "$144/360 \\cdot 100\\%$." },
    { level: 3, title: "Разбор", body: "$144/360 = 0{,}4 = 40\\%$." },
  ],
  solution: [
    "$144/360 = 0{,}4 = 40\\%$.",
  ],
  relatedHandbookTopics: ["hb-statistics-graphs"],
},
{
  id: "stat-median-10",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Медиана",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Найдите медиану ряда: 1, 3, 5, 7, 9, 11, 13, 15, 17, 19.",
  answer: { kind: "numeric", value: 10, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "10 чисел — чётное, медиана = среднее двух центральных." },
    { level: 2, title: "План", body: "Центральные: 5-й и 6-й, то есть 9 и 11." },
    { level: 3, title: "Разбор", body: "Медиана = $(9+11)/2 = 10$." },
  ],
  solution: [
    "Ряд упорядочен.",
    "Центральные: 9 и 11.",
    "Медиана = 10.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-two-averages",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Среднее",
  difficulty: "hard",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В первой группе 10 человек со средним ростом 170 см. Во второй группе 15 человек со средним ростом 180 см. Найдите средний рост всех 25 человек.",
  answer: { kind: "numeric", value: 176, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Найдите суммарный рост в каждой группе." },
    { level: 2, title: "План", body: "Суммы: $10 \\cdot 170 = 1700$ и $15 \\cdot 180 = 2700$." },
    { level: 3, title: "Разбор", body: "Всего: $(1700+2700)/25 = 4400/25 = 176$." },
  ],
  solution: [
    "Сумма: $1700 + 2700 = 4400$.",
    "Средний: $4400/25 = 176$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-temperature-deviation",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Отклонения",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В течение 5 дней температура была 10, 12, 11, 13, 9. На сколько градусов самая высокая температура отличается от средней?",
  answer: { kind: "numeric", value: 2, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Средняя: сложить и поделить на 5." },
    { level: 2, title: "План", body: "Средняя: $(10+12+11+13+9)/5 = 55/5 = 11$." },
    { level: 3, title: "Разбор", body: "Максимум = 13. Отклонение = $13 - 11 = 2$." },
  ],
  solution: [
    "Средняя: 11.",
    "Максимум: 13.",
    "Разность: 2.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-sample-size",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Частота",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В выборке из 80 деталей оказалось 4 бракованных. Найдите относительную частоту брака в виде десятичной дроби.",
  answer: { kind: "numeric", value: 0.05, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "Брак/всего." },
    { level: 2, title: "План", body: "$4/80$." },
    { level: 3, title: "Разбор", body: "$4/80 = 0{,}05$." },
  ],
  solution: [
    "$4/80 = 0{,}05$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-discount",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Проценты",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Товар стоил 800 рублей. После скидки он стоит 640 рублей. Какой процент составляет скидка?",
  answer: { kind: "numeric", value: 20, tolerance: 0.1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Скидка в рублях: 800-640." },
    { level: 2, title: "План", body: "Относительно исходной цены." },
    { level: 3, title: "Разбор", body: "$160/800 = 0{,}2 = 20\\%$." },
  ],
  solution: [
    "Скидка: $800-640 = 160$.",
    "$160/800 = 20\\%$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-population-growth",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Проценты",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "Население города в 2020 году было 120 000 человек. К 2023 году оно выросло на 5%. Сколько человек стало в городе в 2023 году?",
  answer: { kind: "numeric", value: 126000, tolerance: 1 },
  hints: [
    { level: 1, title: "Подсказка", body: "Коэффициент роста: 1,05." },
    { level: 2, title: "План", body: "Умножить на 1,05." },
    { level: 3, title: "Разбор", body: "$120000 \\cdot 1{,}05 = 126000$." },
  ],
  solution: [
    "$120000 \\cdot 1{,}05 = 126000$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-class-grades",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Среднее",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В классе 20 учеников написали контрольную. 5 получили «5», 8 — «4», 5 — «3», 2 — «2». Найдите средний балл.",
  answer: { kind: "numeric", value: 3.8, tolerance: 0.01 },
  hints: [
    { level: 1, title: "Подсказка", body: "Взвешенное среднее." },
    { level: 2, title: "План", body: "$\\bar x = (5 \\cdot 5 + 4 \\cdot 8 + 3 \\cdot 5 + 2 \\cdot 2)/20$." },
    { level: 3, title: "Разбор", body: "$\\bar x = (25+32+15+4)/20 = 76/20 = 3{,}8$." },
  ],
  solution: [
    "$\\bar x = (25+32+15+4)/20 = 76/20 = 3{,}8$.",
  ],
  relatedHandbookTopics: ["hb-statistics-averages"],
},
{
  id: "stat-midrange",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Средние и экстремумы",
  difficulty: "easy",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "В ряду чисел 12, 19, 8, 25, 14, 17 найдите размах.",
  answer: { kind: "numeric", value: 17, tolerance: 0.001 },
  hints: [
    { level: 1, title: "Подсказка", body: "max - min." },
    { level: 2, title: "План", body: "max = 25, min = 8." },
    { level: 3, title: "Разбор", body: "$25 - 8 = 17$." },
  ],
  solution: [
    "max = 25, min = 8.",
    "$R = 17$.",
  ],
  relatedHandbookTopics: ["hb-statistics-spread"],
},
{
  id: "stat-hist-reading",
  topic: "statistics",
  examNumber: 9,
  examLevel: "база",
  subtopic: "Чтение диаграмм",
  difficulty: "medium",
  source: "Открытый банк ФИПИ (тип задания)",
  statement: "По данным столбчатой диаграммы продаж: январь 10, февраль 15, март 20, апрель 25 тысяч штук. На сколько процентов апрель больше января?",
  answer: { kind: "numeric", value: 150, tolerance: 0.5 },
  hints: [
    { level: 1, title: "Подсказка", body: "Рост = (новое - старое)/старое * 100%." },
    { level: 2, title: "План", body: "$(25-10)/10 \\cdot 100\\%$." },
    { level: 3, title: "Разбор", body: "$15/10 = 1{,}5 = 150\\%$." },
  ],
  solution: [
    "Рост = $(25-10)/10 = 1{,}5 = 150\\%$.",
  ],
  relatedHandbookTopics: ["hb-statistics-graphs"],
},
];
